2022-01-27 15:02:47,382 ERROR: Exception on /index [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 114, in index
    data_dumps = json.dumps(data)
  File "C:\Program Files (x86)\Python37-32\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2022-01-27 15:02:56,357 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-27 15:04:51,691 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-27 15:06:59,650 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:22:59,066 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:29:19,447 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:32:54,446 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:36:10,301 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:40:15,726 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:42:33,407 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:43:46,023 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:45:00,126 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:45:36,963 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:47:32,098 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:52:03,400 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:52:36,390 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:52:43,860 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:54:08,802 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:59:40,497 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 14:59:50,997 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 15:00:46,423 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 15:01:22,867 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 15:01:30,673 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 15:02:09,485 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-28 15:02:11,898 ERROR: Exception on / [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 118, in index
    return render_template('index.html', title='Home', posts1=posts1, posts2 = posts2, posts3 = posts3, dataDict = dataDict)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Led-Lights\webApp\app\templates\index.html", line 46, in template
    <td>{{ scene.brightness }} {{  }} {{  }} {{  }} {{  }} </td>
jinja2.exceptions.TemplateSyntaxError: Expected an expression, got 'end of print statement'
2022-01-28 15:02:23,770 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:28:20,927 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:38:22,241 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:39:07,189 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:39:59,261 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:40:44,203 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:42:36,986 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:43:33,569 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:43:36,339 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:46:30,514 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:50:38,864 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:53:28,226 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:54:26,137 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:55:21,001 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 14:57:32,813 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 15:08:04,824 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-01-31 15:08:05,901 ERROR: Exception on / [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 119, in index
    sch_date = datetime.datetime.strptime(i["start_time"], '%Y-%m-%dT%H:%M:%S.%f')
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2022-01-31 15:09:10,523 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
