2022-03-09 14:41:25,770 ERROR: Exception on /addscene [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 393, in addscene
    return render_template('editScedual.html', title='Add Scene', form=form)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: editScedual.html
2022-03-09 14:41:40,734 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-09 14:41:42,641 ERROR: Exception on /addscene [GET] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 393, in addscene
    return render_template('editScedule.html', title='Add Scene', form=form)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\led-lights\webapp\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: editScedule.html
2022-03-09 14:42:15,497 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-09 14:43:41,103 ERROR: Exception on /addscene [POST] [in c:\led-lights\webapp\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\led-lights\webapp\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\led-lights\webapp\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Led-Lights\webApp\app\routes.py", line 366, in addscene
    "id": id,
UnboundLocalError: local variable 'id' referenced before assignment
2022-03-09 14:44:39,398 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-10 14:38:11,372 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-11 14:39:50,991 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-11 14:44:16,364 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-11 14:45:10,580 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-11 15:08:05,766 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
2022-03-17 14:51:26,543 INFO: WebApp startup [in C:\Led-Lights\webApp\app\__init__.py:45]
